#This is the configuration file for WS2 computations
#the format is key=value
#matches: key=value
# my-key = value
# my.key= value with spaces
#KEY_NAME =   value123
# complex-key.name = some value here
#does not match:
# = value              # No key
# key =                # No value, this must be filled
# key value            # No equals sign
# my key = value       # Space in key (not allowed)
# key==value          # Multiple equals (first = becomes part of key)

#name of the system
name=WS2

#dimension of system
dim=2

#directions to study, available directions x,y,z
directions_to_study=x,y

#whether spin is considered
spin=False

truncation_radius=12

lattice_basis=3.5186, 0.0, 0.0; 0.0, 6.3023, 0.0; 0.0, 0.0, 15.0058


space_group=11

space_group_origin=0,0,0

space_group_name_H_M=P21/M

cell_setting=monoclinic

Wyckoff_position_num=3


#Wyckoff position label W0, input orbitals
W0_orbitals=5dx2-y2
#one position of W0, coefficients  (fractional coordinates)
W0_position_coefs=0.25, 0.17781, 0.99281

#Wyckoff position label S0, input orbitals
S0_orbitals=3px
#one position of S0, coefficients  (fractional coordinates)
S0_position_coefs=0.25, 0.57392, 0.90271

#Wyckoff position label S1, input orbitals
#S1_orbitals=
#one position of S1, coefficients  (fractional coordinates)
#S1_position_coefs=0.75, 0.42608, 0.09729
